#!/bin/bash


#realtive path to this script
cd ~/Geometry/Geometry-Book/

#update output files
mdbook build 

#implement preferences
cd config_files
./add_icons.py
./add_comment_dialog.py
./wrap_sections.py
./import_styles.py
./import_scripts.py

mkdir -p ../book/config_files

cp -R css ../book/config_files
cp -R js  ../book/config_files

# cp -R css/icons ../book/config_files/css
cp -R theme/css/* ../book/css/
cp -R theme/css/* ../book/
cp -R theme/* ../book/

cd ..

cd book
echo "geominpix.cf" > CNAME

cd ..

# echo $PWD

#cd ~Desktop/Geometry\ Book
#rm -rf !(".git")
# rm -rf ~/Desktop/Geometry-Book/*
#cd ~/Geometry/Geometry\ Book/

# cp -R book/*  ~/Desktop/Geometry-Book/

case $1 in 
	-o | --open)
		cd book && $BROWSER index.html &> /dev/null #run index.html to view changes
        ;;
esac
